/* Auto-generated by genmsg_cpp for file /home/bajo/workspace/tuw_acin_eva2/tuw_acin_eva_servo/msg/ServoSpeed.msg */
#ifndef TUW_ACIN_EVA_SERVO_MESSAGE_SERVOSPEED_H
#define TUW_ACIN_EVA_SERVO_MESSAGE_SERVOSPEED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace tuw_acin_eva_servo
{
template <class ContainerAllocator>
struct ServoSpeed_ {
  typedef ServoSpeed_<ContainerAllocator> Type;

  ServoSpeed_()
  : pan_speed(0)
  , tilt_speed(0)
  {
  }

  ServoSpeed_(const ContainerAllocator& _alloc)
  : pan_speed(0)
  , tilt_speed(0)
  {
  }

  typedef int32_t _pan_speed_type;
  int32_t pan_speed;

  typedef int32_t _tilt_speed_type;
  int32_t tilt_speed;


  typedef boost::shared_ptr< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ServoSpeed
typedef  ::tuw_acin_eva_servo::ServoSpeed_<std::allocator<void> > ServoSpeed;

typedef boost::shared_ptr< ::tuw_acin_eva_servo::ServoSpeed> ServoSpeedPtr;
typedef boost::shared_ptr< ::tuw_acin_eva_servo::ServoSpeed const> ServoSpeedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace tuw_acin_eva_servo

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1308e18703a9a36af635dc7306ba5e60";
  }

  static const char* value(const  ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1308e18703a9a36aULL;
  static const uint64_t static_value2 = 0xf635dc7306ba5e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tuw_acin_eva_servo/ServoSpeed";
  }

  static const char* value(const  ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 pan_speed\n\
int32 tilt_speed\n\
\n\
";
  }

  static const char* value(const  ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pan_speed);
    stream.next(m.tilt_speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ServoSpeed_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::tuw_acin_eva_servo::ServoSpeed_<ContainerAllocator> & v) 
  {
    s << indent << "pan_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pan_speed);
    s << indent << "tilt_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tilt_speed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TUW_ACIN_EVA_SERVO_MESSAGE_SERVOSPEED_H

