(cl:defpackage tuw_acin_eva_people-msg
  (:use )
  (:export
   "<DOHEADMOVEACTION>"
   "DOHEADMOVEACTION"
   "<DOHEADMOVEACTIONRESULT>"
   "DOHEADMOVEACTIONRESULT"
   "<DOHEADMOVEACTIONFEEDBACK>"
   "DOHEADMOVEACTIONFEEDBACK"
   "<DOHEADMOVERESULT>"
   "DOHEADMOVERESULT"
   "<DOHEADMOVEFEEDBACK>"
   "DOHEADMOVEFEEDBACK"
   "<DOHEADMOVEGOAL>"
   "DOHEADMOVEGOAL"
   "<DOHEADMOVEACTIONGOAL>"
   "DOHEADMOVEACTIONGOAL"
  ))

