; Auto-generated. Do not edit!


(cl:in-package tuw_acin_eva_people-msg)


;//! \htmlinclude DoHeadMoveActionGoal.msg.html

(cl:defclass <DoHeadMoveActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type tuw_acin_eva_people-msg:DoHeadMoveGoal
    :initform (cl:make-instance 'tuw_acin_eva_people-msg:DoHeadMoveGoal)))
)

(cl:defclass DoHeadMoveActionGoal (<DoHeadMoveActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoHeadMoveActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoHeadMoveActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_acin_eva_people-msg:<DoHeadMoveActionGoal> is deprecated: use tuw_acin_eva_people-msg:DoHeadMoveActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <DoHeadMoveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:header-val is deprecated.  Use tuw_acin_eva_people-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <DoHeadMoveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:goal_id-val is deprecated.  Use tuw_acin_eva_people-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <DoHeadMoveActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:goal-val is deprecated.  Use tuw_acin_eva_people-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoHeadMoveActionGoal>) ostream)
  "Serializes a message object of type '<DoHeadMoveActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoHeadMoveActionGoal>) istream)
  "Deserializes a message object of type '<DoHeadMoveActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoHeadMoveActionGoal>)))
  "Returns string type for a message object of type '<DoHeadMoveActionGoal>"
  "tuw_acin_eva_people/DoHeadMoveActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoHeadMoveActionGoal)))
  "Returns string type for a message object of type 'DoHeadMoveActionGoal"
  "tuw_acin_eva_people/DoHeadMoveActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoHeadMoveActionGoal>)))
  "Returns md5sum for a message object of type '<DoHeadMoveActionGoal>"
  "4b3cc1cde6af499dea410066964f0c31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoHeadMoveActionGoal)))
  "Returns md5sum for a message object of type 'DoHeadMoveActionGoal"
  "4b3cc1cde6af499dea410066964f0c31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoHeadMoveActionGoal>)))
  "Returns full string definition for message of type '<DoHeadMoveActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%DoHeadMoveGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tuw_acin_eva_people/DoHeadMoveGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] target_pos # desired position of the head  ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoHeadMoveActionGoal)))
  "Returns full string definition for message of type 'DoHeadMoveActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%DoHeadMoveGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tuw_acin_eva_people/DoHeadMoveGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] target_pos # desired position of the head  ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoHeadMoveActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoHeadMoveActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoHeadMoveActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
