; Auto-generated. Do not edit!


(cl:in-package tuw_acin_eva_people-msg)


;//! \htmlinclude DoHeadMoveResult.msg.html

(cl:defclass <DoHeadMoveResult> (roslisp-msg-protocol:ros-message)
  ((pos_reached
    :reader pos_reached
    :initarg :pos_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DoHeadMoveResult (<DoHeadMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoHeadMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoHeadMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_acin_eva_people-msg:<DoHeadMoveResult> is deprecated: use tuw_acin_eva_people-msg:DoHeadMoveResult instead.")))

(cl:ensure-generic-function 'pos_reached-val :lambda-list '(m))
(cl:defmethod pos_reached-val ((m <DoHeadMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:pos_reached-val is deprecated.  Use tuw_acin_eva_people-msg:pos_reached instead.")
  (pos_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoHeadMoveResult>) ostream)
  "Serializes a message object of type '<DoHeadMoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'pos_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoHeadMoveResult>) istream)
  "Deserializes a message object of type '<DoHeadMoveResult>"
    (cl:setf (cl:slot-value msg 'pos_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoHeadMoveResult>)))
  "Returns string type for a message object of type '<DoHeadMoveResult>"
  "tuw_acin_eva_people/DoHeadMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoHeadMoveResult)))
  "Returns string type for a message object of type 'DoHeadMoveResult"
  "tuw_acin_eva_people/DoHeadMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoHeadMoveResult>)))
  "Returns md5sum for a message object of type '<DoHeadMoveResult>"
  "fab0abf234bba009b5a10cefef47651f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoHeadMoveResult)))
  "Returns md5sum for a message object of type 'DoHeadMoveResult"
  "fab0abf234bba009b5a10cefef47651f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoHeadMoveResult>)))
  "Returns full string definition for message of type '<DoHeadMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool pos_reached # True if desired position has is reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoHeadMoveResult)))
  "Returns full string definition for message of type 'DoHeadMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool pos_reached # True if desired position has is reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoHeadMoveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoHeadMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoHeadMoveResult
    (cl:cons ':pos_reached (pos_reached msg))
))
