; Auto-generated. Do not edit!


(cl:in-package tuw_acin_eva_people-msg)


;//! \htmlinclude DoHeadMoveGoal.msg.html

(cl:defclass <DoHeadMoveGoal> (roslisp-msg-protocol:ros-message)
  ((target_pos
    :reader target_pos
    :initarg :target_pos
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass DoHeadMoveGoal (<DoHeadMoveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoHeadMoveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoHeadMoveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_acin_eva_people-msg:<DoHeadMoveGoal> is deprecated: use tuw_acin_eva_people-msg:DoHeadMoveGoal instead.")))

(cl:ensure-generic-function 'target_pos-val :lambda-list '(m))
(cl:defmethod target_pos-val ((m <DoHeadMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:target_pos-val is deprecated.  Use tuw_acin_eva_people-msg:target_pos instead.")
  (target_pos m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoHeadMoveGoal>) ostream)
  "Serializes a message object of type '<DoHeadMoveGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'target_pos))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'target_pos))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoHeadMoveGoal>) istream)
  "Deserializes a message object of type '<DoHeadMoveGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'target_pos) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'target_pos)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoHeadMoveGoal>)))
  "Returns string type for a message object of type '<DoHeadMoveGoal>"
  "tuw_acin_eva_people/DoHeadMoveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoHeadMoveGoal)))
  "Returns string type for a message object of type 'DoHeadMoveGoal"
  "tuw_acin_eva_people/DoHeadMoveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoHeadMoveGoal>)))
  "Returns md5sum for a message object of type '<DoHeadMoveGoal>"
  "1be25714438ab86e85b332a6800576b0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoHeadMoveGoal)))
  "Returns md5sum for a message object of type 'DoHeadMoveGoal"
  "1be25714438ab86e85b332a6800576b0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoHeadMoveGoal>)))
  "Returns full string definition for message of type '<DoHeadMoveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] target_pos # desired position of the head  ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoHeadMoveGoal)))
  "Returns full string definition for message of type 'DoHeadMoveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32[] target_pos # desired position of the head  ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoHeadMoveGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'target_pos) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoHeadMoveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoHeadMoveGoal
    (cl:cons ':target_pos (target_pos msg))
))
