; Auto-generated. Do not edit!


(cl:in-package tuw_acin_eva_people-msg)


;//! \htmlinclude DoHeadMoveFeedback.msg.html

(cl:defclass <DoHeadMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pos
    :reader current_pos
    :initarg :current_pos
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass DoHeadMoveFeedback (<DoHeadMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoHeadMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoHeadMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tuw_acin_eva_people-msg:<DoHeadMoveFeedback> is deprecated: use tuw_acin_eva_people-msg:DoHeadMoveFeedback instead.")))

(cl:ensure-generic-function 'current_pos-val :lambda-list '(m))
(cl:defmethod current_pos-val ((m <DoHeadMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tuw_acin_eva_people-msg:current_pos-val is deprecated.  Use tuw_acin_eva_people-msg:current_pos instead.")
  (current_pos m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoHeadMoveFeedback>) ostream)
  "Serializes a message object of type '<DoHeadMoveFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_pos))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'current_pos))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoHeadMoveFeedback>) istream)
  "Deserializes a message object of type '<DoHeadMoveFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_pos) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_pos)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoHeadMoveFeedback>)))
  "Returns string type for a message object of type '<DoHeadMoveFeedback>"
  "tuw_acin_eva_people/DoHeadMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoHeadMoveFeedback)))
  "Returns string type for a message object of type 'DoHeadMoveFeedback"
  "tuw_acin_eva_people/DoHeadMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoHeadMoveFeedback>)))
  "Returns md5sum for a message object of type '<DoHeadMoveFeedback>"
  "26a282a599ced22fefe3f7297a70c666")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoHeadMoveFeedback)))
  "Returns md5sum for a message object of type 'DoHeadMoveFeedback"
  "26a282a599ced22fefe3f7297a70c666")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoHeadMoveFeedback>)))
  "Returns full string definition for message of type '<DoHeadMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32[] current_pos # current position of the head~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoHeadMoveFeedback)))
  "Returns full string definition for message of type 'DoHeadMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32[] current_pos # current position of the head~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoHeadMoveFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_pos) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoHeadMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DoHeadMoveFeedback
    (cl:cons ':current_pos (current_pos msg))
))
