/* Auto-generated by genmsg_cpp for file /home/bajo/workspace/tuw_acin_eva2/tuw_acin_eva_people/msg/DoHeadMoveGoal.msg */
#ifndef TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEGOAL_H
#define TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace tuw_acin_eva_people
{
template <class ContainerAllocator>
struct DoHeadMoveGoal_ {
  typedef DoHeadMoveGoal_<ContainerAllocator> Type;

  DoHeadMoveGoal_()
  : target_pos()
  {
  }

  DoHeadMoveGoal_(const ContainerAllocator& _alloc)
  : target_pos(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _target_pos_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  target_pos;


  typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DoHeadMoveGoal
typedef  ::tuw_acin_eva_people::DoHeadMoveGoal_<std::allocator<void> > DoHeadMoveGoal;

typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveGoal> DoHeadMoveGoalPtr;
typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveGoal const> DoHeadMoveGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace tuw_acin_eva_people

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1be25714438ab86e85b332a6800576b0";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1be25714438ab86eULL;
  static const uint64_t static_value2 = 0x85b332a6800576b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tuw_acin_eva_people/DoHeadMoveGoal";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float32[] target_pos # desired position of the head  \n\
\n\
";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.target_pos);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DoHeadMoveGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> & v) 
  {
    s << indent << "target_pos[]" << std::endl;
    for (size_t i = 0; i < v.target_pos.size(); ++i)
    {
      s << indent << "  target_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.target_pos[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEGOAL_H

