/* Auto-generated by genmsg_cpp for file /home/bajo/workspace/tuw_acin_eva2/tuw_acin_eva_people/msg/DoHeadMoveActionGoal.msg */
#ifndef TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEACTIONGOAL_H
#define TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "tuw_acin_eva_people/DoHeadMoveGoal.h"

namespace tuw_acin_eva_people
{
template <class ContainerAllocator>
struct DoHeadMoveActionGoal_ {
  typedef DoHeadMoveActionGoal_<ContainerAllocator> Type;

  DoHeadMoveActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  DoHeadMoveActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator>  _goal_type;
   ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DoHeadMoveActionGoal
typedef  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<std::allocator<void> > DoHeadMoveActionGoal;

typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveActionGoal> DoHeadMoveActionGoalPtr;
typedef boost::shared_ptr< ::tuw_acin_eva_people::DoHeadMoveActionGoal const> DoHeadMoveActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace tuw_acin_eva_people

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4b3cc1cde6af499dea410066964f0c31";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4b3cc1cde6af499dULL;
  static const uint64_t static_value2 = 0xea410066964f0c31ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tuw_acin_eva_people/DoHeadMoveActionGoal";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
DoHeadMoveGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: tuw_acin_eva_people/DoHeadMoveGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float32[] target_pos # desired position of the head  \n\
\n\
";
  }

  static const char* value(const  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DoHeadMoveActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::tuw_acin_eva_people::DoHeadMoveActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::tuw_acin_eva_people::DoHeadMoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TUW_ACIN_EVA_PEOPLE_MESSAGE_DOHEADMOVEACTIONGOAL_H

